[book]
authors      = ["Miden contributors"]
description  = "Documentation for the Miden STARK-based virtual machine"
language     = "en"
multilingual = false
title        = "The Miden virtual machine"

[output.html]
git-repository-url = "https://github.com/0xPolygonMiden/miden-vm"

[preprocessor.katex]
after = ["links"]

[preprocessor.alerts]

[output.linkcheck]
